steps:
  # Instalar dependencias del backend
  - name: 'node:18'
    dir: 'backend'
    entrypoint: npm
    args: ['install']

  # Instalar dependencias del frontend
  - name: 'node:18'
    dir: 'frontend'
    entrypoint: npm
    args: ['install']

  # Construir el frontend
  - name: 'node:18'
    dir: 'frontend'
    entrypoint: npm
    args: ['run', 'build']

  # Copiar archivos estáticos del frontend al backend
  - name: 'bash'
    args: ['-c', 'mkdir -p backend/public && cp -r frontend/dist/* backend/public/']

  # Desplegar en Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--source=./backend'
      - '--region=${_DEPLOY_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=1Gi'
      - '--cpu=1'
      - '--max-instances=10'
      - '--min-instances=1'
      - '--port=8080'
      - '--set-env-vars=NODE_ENV=production,PORT=8080'
      - '--timeout=300s'

substitutions:
  _SERVICE_NAME: gatelogix
  _DEPLOY_REGION: northamerica-south1

options:
  logging: CLOUD_LOGGING_ONLY