apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: gatelogix
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "10"
        run.googleapis.com/startup-cpu-boost: "true"
        run.googleapis.com/cpu-throttling: "true"
        run.googleapis.com/cloudsql-instances: ""
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
        - image: ${IMAGE}
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
          env:
            - name: NODE_ENV
              value: "production"
            # PORT es establecido automáticamente por Cloud Run; no definirlo explícitamente
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb-credentials
                  key: uri
          startupProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30